---
- name: Create Prometheus user
  user:
    name: "{{ prometheus_user }}"
    system: yes
    shell: /sbin/nologin

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0755'
  loop:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"
    - "{{ prometheus_log_dir }}"
    - "{{ prometheus_install_dir }}"

- name: Download Prometheus tarball
  get_url:
    url: "{{ prometheus_download_url }}"
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus archive
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: "{{ prometheus_install_dir }}"
    remote_src: yes

- name: Move Prometheus binaries
  command: mv "{{ prometheus_install_dir }}/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}" "/usr/local/bin/{{ item }}"
  args:
    removes: "{{ prometheus_install_dir }}/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
  loop:
    - prometheus
    - promtool

- name: Set correct permissions for Prometheus binaries
  file:
    path: "/usr/local/bin/{{ item }}"
    mode: '0755'
  loop:
    - prometheus
    - promtool


- name: Deploy Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0644'
  notify: Restart Prometheus

- name: Create Prometheus systemd service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/{{ prometheus_service_name }}.service
  notify: Restart Prometheus

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start Prometheus service
  systemd:
    name: "{{ prometheus_service_name }}"
    enabled: yes
    state: started

# ========== ALERTMANAGER INSTALLATION ==========

- name: Create Alertmanager directory
  file:
    path: "{{ alertmanager_config_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0755'

- name: Create Alertmanager installation directory
  file:
    path: "{{ alertmanager_install_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0755'

- name: Download Alertmanager tarball
  get_url:
    url: "{{ alertmanager_download_url }}"
    dest: /tmp/alertmanager.tar.gz

- name: Extract Alertmanager archive
  unarchive:
    src: /tmp/alertmanager.tar.gz
    dest: "{{ alertmanager_install_dir }}"
    remote_src: yes
    extra_opts:
      - --strip-components=1  

- name: Move Alertmanager binaries
  copy:
    src: "{{ alertmanager_install_dir }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}" 
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  loop:
    - alertmanager
    - amtool

- name: Ensure Alertmanager binary is executable
  file:
    path: "/usr/local/bin/alertmanager"
    mode: '0755'

- name: Deploy Alertmanager configuration
  template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0644'
  notify: Restart Alertmanager

- name: Create Alertmanager systemd service
  template:
    src: alertmanager.service.j2
    dest: "/etc/systemd/system/{{ alertmanager_service_name }}.service"
  notify: Restart Alertmanager

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start Alertmanager service
  systemd:
    name: "{{ alertmanager_service_name }}"
    enabled: yes
    state: started
- name: Create Prometheus rules directory
  file:
    path: "{{ prometheus_config_dir }}/rules"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0755'

- name: Deploy Prometheus Rules
  template:
    src: rules.yml.j2
    dest: "{{ prometheus_config_dir }}/rules/rules.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0644'
  notify: Restart Prometheus



- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create .htpasswd file for authentication
  shell: echo "{{ prometheus_user }}:$(openssl passwd -crypt {{ prometheus_password }})" > /etc/nginx/.htpasswd
  args:
    creates: /etc/nginx/.htpasswd

- name: Deploy Nginx config for Prometheus
  template:
    src: nginx_prometheus.j2
    dest: /etc/nginx/sites-available/prometheus
  notify: Restart Nginx

- name: Enable Prometheus Nginx site
  file:
    src: /etc/nginx/sites-available/prometheus
    dest: /etc/nginx/sites-enabled/prometheus
    state: link
  notify: Restart Nginx

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted
